//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppV0._1.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdVisitor { get; set; }
        public Nullable<int> IdRoom { get; set; }
        public string Message { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
