//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppV0._1.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int IdUser { get; set; }
        public string Nick { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
